### ISSUE TITLE
Finish after each session in schedule

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/study-groups#12]
I'm guessing this is something to do with the way we are making a multi-day schedule but is it possible to remove the "Finish" lines after each episode in the schedule?  I think it makes the schedule a bit hard to read.

**Comment by tobyhodges** [comment]
There are a few things I would like to change about the Syllabus table for this program, e.g. listing each section as "Week" rather than "Day." I will try to get to this next week, but I don't consider it vital to fix before the first round begins.
