### ISSUE TITLE
Ice Breaker tips for Facilitators 

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/study-groups#49]
Group Facilitators will lead the ice breaker in future rounds. We should provide some suggested ice breakers for Group Facilitators, and some guidance for maximum duration.

**Comment by tobyhodges** [comment]
This can link to [the list of icebreakers from the Instructor Training curriculum](https://carpentries.github.io/instructor-training/icebreakers/index.html), but I also liked these other ice breakers from this round:

- What is your favorite Icebreaker question? (this is quite meta, maybe better left for later in the round...)
- How do you feel about snow?
- If you could learn a new skill/domain instantly "Matrix-style" what would you choose and why?
- If you could have the power of teleportation right now, where would you go and why?
- What is one nice thing that happened to you this week? And what are you looking forward to about next week?

**Comment by sstevens2** [comment]
Will work on PR in the next couple days for this issue
