### ISSUE TITLE
Rotating Roles Schedule

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/study-groups#8]
PR #7 got me thinking.  Will we set the schedule for rotating roles?   Maybe we should add something about how the schedule will be created?

**Comment by tobyhodges** [comment]
I was planning to set the role schedule myself. But it could be a task for the Group Facilitators. Do you have a preference?

For the first week, I think (one of) the Group Facilitator(s) should be Discussion Lead, and I will take notes. After that, it is over to the participants.

**Comment by sstevens2** [comment]
That sounds like a good plan.  Maybe we should add something about how this schedule is created to the introduction page?
